=== Maroslav/PressToPlay/Assets/Resources/Scenarios/scenario_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="scenario_schema"
    targetNamespace="http://presstoplaygame.com/scenario"
    elementFormDefault="qualified"
    xmlns="http://presstoplaygame.com/scenario"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:simpleType name="attributenametype">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:pattern value="[a-zA-Z_]*"/>
      <xs:maxLength value="30" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="attributeoperationtype" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="greater"/>
      <xs:enumeration value="less"/>
      <xs:enumeration value="lessOrEqual"/>
      <xs:enumeration value="equal"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="attributevaluetype" >
    <xs:restriction base="xs:int"> 
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="preconditiontype">
    <xs:attribute name="attribute" type="attributenametype"  use="required"/>
    <xs:attribute name="operation" type="attributeoperationtype" use="required"/>
    <xs:attribute name="value" type="attributevaluetype" use="required"/>
  </xs:complexType>


  <xs:complexType name="pressevent">
    <xs:sequence>
      <xs:element name="Preconditions" type="preconditionlist" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="date" type="xs:date" use="optional"/>
  </xs:complexType>
  <xs:complexType name="preconditionlist">
    <xs:sequence>
      <xs:element name="Precondition" type ="preconditiontype" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="effecttype">
    <xs:attribute name="attribute" type="attributenametype"/>
  </xs:complexType>
  <xs:simpleType name="modifyvaluetype">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="-1000"/>
      <xs:maxInclusive value="+1000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="movetowardseffecttype">
    <xs:complexContent>
      <xs:extension base="effecttype">
        <xs:attribute name="value" type="attributevaluetype"/>
        <xs:attribute name="amount" type="attributevaluetype"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="seteffecttype">
    <xs:complexContent>
      <xs:extension base="effecttype">
        <xs:attribute name="value" type="attributevaluetype"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="modifyeffecttype">
    <xs:complexContent>
      <xs:extension base="effecttype">
        <xs:attribute name="value" type="modifyvaluetype"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="effectlisttype">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="MoveTowardsEffect" type="movetowardseffecttype"/>
      <xs:element name="ModifyEffect" type="modifyeffecttype"/>
      <xs:element name="SetEffect" type="seteffecttype"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="choicetype">
    <xs:sequence>
      <xs:element name="Effects" type="effectlisttype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="textchoicetype">
    <xs:complexContent>
      <xs:extension base="choicetype">
        <xs:sequence>
          <xs:element name="Title" type="xs:string"/>
          <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="textchoiceslist">
    <xs:sequence>
      <xs:element name="Choice" type="textchoicetype" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="multiplechoiceeventtype">
    <xs:complexContent>
      <xs:extension base="pressevent">
        <xs:sequence>
          <xs:element name="Description" type="xs:string"/>
          <xs:element name="Choices" type="textchoiceslist"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="pathtoimagetype" >
    <xs:restriction base="xs:anyURI">
      <xs:annotation>
        <xs:documentation>
          Path without file suffix!
        </xs:documentation>
      </xs:annotation>
      <xs:pattern  value="[a-zA-Z0-9_ /]*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="imagechoicetype">
    <xs:complexContent>
      <xs:extension base="choicetype">
        <xs:sequence>
          <xs:element name="ImagePath" type="pathtoimagetype"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="imagechoicelisttype">
    <xs:sequence>
      <xs:element name="Choice" type="imagechoicetype" minOccurs="0" maxOccurs="unbounded"/> 
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="imagechoiceeventtype">
    <xs:complexContent>
      <xs:extension base="pressevent">
        <xs:sequence>
          <xs:element name="Description" type="xs:string"/>
          <xs:element name="Choices" type="imagechoicelisttype"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="cutsceneeventtype">
    <xs:complexContent>
      <xs:extension base="pressevent">
        <xs:sequence>
          <xs:element name="ImagePath" type="pathtoimagetype" />
          <xs:element name="Text" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="eventlisttype">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="MultipleChoiceEvent" type="multiplechoiceeventtype" />
      <xs:element name="ImageChoiceEvent" type="imagechoiceeventtype" />
      <xs:element name="CutsceneEvent" type="cutsceneeventtype" />
    </xs:choice>
  </xs:complexType>
  <xs:element name="Scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Events" type="eventlisttype"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Maroslav/PressToPlay/Assets/Editor/Resources/Attributes/test_story_effects.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario name="name, only for the designer"
          xmlns="http://presstoplaygame.com/scenario"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://presstoplaygame.com/scenario ../../../Resources/Scenarios/scenario_schema.xsd"
          >
  <Events>
      <MultipleChoiceEvent>
          <Description>Event 1 description
          </Description>
          <Choices>
              <Choice>
                  <Effects>
                  </Effects>
                  <Title>Choice 1</Title>
                  <Description>
                      Choice 1 description
                  </Description>
              </Choice>
              <Choice>
                  <Effects>
                      <ModifyEffect attribute="abc" value="150"/>
                      <MoveTowardsEffect amount="100" attribute="attrib_name" value="500"/>
                  </Effects>
                  <Title>Choice 2 title</Title>
                  <Description>
                      Choice 2 long description
                  </Description>
              </Choice>
          </Choices>
      </MultipleChoiceEvent>
  </Events>
</Scenario>

=== Maroslav/PressToPlay/Assets/Resources/Scenarios/random.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario name="name, only for the designer" 
     xmlns="http://presstoplaygame.com/scenario"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://presstoplaygame.com/scenario scenario_schema.xsd"
          >
  <Events>
    <MultipleChoiceEvent >
      <Description>Policie pohřešuje osmiletou holčičku Aničku Novákovou.</Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "900"/>
          </Effects>
          <Title>Vyjádření policie</Title>
          <Description>Dívka odešla z domu po páté hodině odpoledne bez mobilního telefonu. Na sobě měla fialové tepláky a zelenkavou šusťákovou bundu.
            V případě, že můžete k výskytu pohřešované podat jakékoliv informace, volejte na bezplatnou linku 158.
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "100"/>
          </Effects>
          <Title> Vyjádření sousedů</Title>
          <Description>Ztracená Anička: Další podezřelý je sexuální deviant! Matka se zhroutila!</Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent>
      <Description>V Něměcku zaznamenáno přes 150.000 trestných činů souvisejících s uprchlickou krizí. 90% těchto činů se týká překročení státní hranice bez platných cestovních dokladů. </Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "1000"/>
          </Effects>
          <Title>Administrativní zátěž</Title>
          <Description>Uprchlická krize především přinesla administrativní zátěž
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "0"/>
          </Effects>
          <Title>Vlna zločinu</Title>
          <Description>Co uprchlík to zločinec. Němci se začínají ozbrojovat.</Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent>
      <Description>Výtěžek ze sbírky pro romskou rodinu paterčat zamrzl na účtu charity. Pro rodinu může být situace likvidační. </Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "800"/>
          </Effects>
          <Title>Věc řeší advokát</Title>
          <Description>
            Věc řeší advokát
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "200"/>
          </Effects>
          <Title>Romská rodina se hádá o peníze ze sbírky</Title>
          <Description> Romská rodina se hádá o peníze ze sbírky.</Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent>
      <Description>V Českých Budějovicích má vzniknout moderní kulturní multiplex od avantgardního architekta. Budova pojme až šest operních sálů.</Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "600"/>
          </Effects>
          <Title>Vyjádření odborníka</Title>
          <Description>
            “Je to unikátní projekt, který zvyší prestiž Českých Budějovic na mezinárodní urovni,” říká k návrhu operního sálu ve tvaru Olihně Tomáš Nejedlý z katedry architektury na ČVUT.
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "400"/>
          </Effects>
          <Title>Anketa</Title>
          <Description>
            Prodavačka Jana (28): A peníze pro důchodce nejsou!
            Důchodkyně Věra (79): Já bych všechny ty multiplexy zakázala!
            Student střední školy (15): Mně se to líbí. Vypadá to jako penis.
          </Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent>
      <Description> Na Teplicku skupují pozemky bohatí developeři z Arabských Emirátů.</Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "900"/>
          </Effects>
          <Title>Velká příležitost</Title>
          <Description>Do chudého regionu doputují milionové investice. Očekává se 10 000 nových pracovních míst.
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "100"/>
          </Effects>
          <Title>Invaze</Title>
          <Description>Muslimští šejkové kolonizují Česko! Sociolog: Je otázkou času, kdy začnou zahalovat naše ženy!</Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent>
      <Description>Vyjádření ministra vlády: “Ty velkoměsta tady začínají ovládat vegetariáni, nekuřáci, transvestiti, cyklisti, homosexuálové a já prostě potřebuju občas utýct na ten venkov, kde jsou ještě normální chlapi a ženský.”
      </Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "750"/>
          </Effects>
          <Title>Ignorovat</Title>
          <Description>
            ...
          </Description>
        </Choice>
        <Choice>
          <Effects>
            <MoveTowardsEffect attribute="Credibility" value = "250"/>
          </Effects>
          <Title>Publikovat</Title>
          <Description>Politik sebral odvahu a řekl natvrdo, co si každý myslí!</Description>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
  </Events>
</Scenario>

=== Maroslav/PressToPlay/Assets/Editor/Resources/Scenarios/test_story.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario name="Story scenario"
  xmlns="http://presstoplaygame.com/scenario"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://presstoplaygame.com/scenario ../../../Resources/Scenarios/scenario_schema.xsd"
          >
  <Events>
    <CutsceneEvent date="1989-11-17">
      <Preconditions>
      </Preconditions>
      <ImagePath>Path/To/Image</ImagePath>
      <Text>Game Start</Text>
    </CutsceneEvent>
    <CutsceneEvent date="1989-11-20">
      <Preconditions>
        <Precondition attribute = "Credibility" operation="lessOrEqual" value="500"/>
      </Preconditions>
      <ImagePath>Path/To/EventLowCredibility</ImagePath>
      <Text>EventLowCredibility</Text>
    </CutsceneEvent>
    <CutsceneEvent date="1989-11-22">
      <Preconditions>
        <Precondition attribute = "Credibility" operation="greater" value="500"/>
      </Preconditions>
      <ImagePath>Path/To/EventHighCredibility</ImagePath>
      <Text>EventHighCredibility</Text>
    </CutsceneEvent>
  </Events>
</Scenario>

=== Maroslav/PressToPlay/Assets/Editor/Resources/Scenarios/test_conditional_attribcmp.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../../Resources/Scenarios/scenario_stylesheet.xslt"?>
<Scenario name="name, only for the designer" xmlns="http://presstoplaygame.com/scenario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://presstoplaygame.com/scenario ../../../Resources/Scenarios/scenario_schema.xsd">
  <Events>
    <MultipleChoiceEvent name="More credibility">
      <Preconditions>
        <Precondition attribute="Credibility" operation="greater" value="Money" />
      </Preconditions>
      <Description>Event 1 description
          </Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Credibility" value="150" />
            <MoveTowardsEffect amount="100" attribute="Credibility" value="500" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent name="More money">
      <Preconditions>
        <Precondition attribute="Credibility" operation="less" value="Money" />
      </Preconditions>
      <Description>More money</Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Credibility" value="150" />
            <MoveTowardsEffect amount="100" attribute="Credibility" value="500" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent name="Little of both">
      <Preconditions>
        <Precondition attribute="Credibility" operation="less" value="200" />
        <Precondition attribute="Money" operation="lessOrEqual" value="Credibility" />
      </Preconditions>
      <Description>More money</Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Credibility" value="150" />
            <MoveTowardsEffect amount="100" attribute="Credibility" value="500" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent name="Late">
      <Preconditions>
        <Precondition attribute="date" operation="greater" value="2016-09-09" />
      </Preconditions>
      <Description>More money</Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Credibility" value="150" />
            <MoveTowardsEffect amount="100" attribute="Credibility" value="500" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
  </Events>
</Scenario>

=== Maroslav/PressToPlay/Assets/Editor/Resources/Scenarios/test_conditional.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../../Resources/Scenarios/scenario_stylesheet.xslt"?>
<Scenario name="name, only for the designer" xmlns="http://presstoplaygame.com/scenario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://presstoplaygame.com/scenario ../../../Resources/Scenarios/scenario_schema.xsd">
  <Events>
    <MultipleChoiceEvent date="2016-11-30">
      <Preconditions>
        <Precondition attribute="Credibility" operation="equal" value="999" />
      </Preconditions>
      <Description>Event 1 description
          </Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Credibility" value="150" />
            <MoveTowardsEffect amount="100" attribute="Credibility" value="500" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent date="2016-11-30">
      <Preconditions>
        <Precondition attribute="Credibility" operation="equal" value="250" />
      </Preconditions>
      <Description>Credibility is 250.</Description>
      <Choices>
        <Choice>
          <Effects>
            <SetEffect attribute="Money" value="0" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects></Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <MultipleChoiceEvent date="2016-12-01">
      <Preconditions>
        <Precondition attribute="Credibility" operation="greater" value="549" />
      </Preconditions>
      <Description>High credibility!</Description>
      <Choices>
        <Choice>
          <Effects>
            <MoveTowardsEffect amount="25" attribute="Money" value="500" />
          </Effects>
          <Description>
                      Choice 1 description
                  </Description>
          <ChoiceText>Choice 1</ChoiceText>
        </Choice>
        <Choice>
          <Effects>
            <ModifyEffect attribute="Money" value="150" />
          </Effects>
          <Description>
                      Choice 2 long description
                  </Description>
          <ChoiceText>Choice 2 ChoiceText</ChoiceText>
        </Choice>
      </Choices>
    </MultipleChoiceEvent>
    <CutsceneEvent>
      <ImagePath>Some/Image/Path</ImagePath>
      <Text>Unconditional conditional!</Text>
    </CutsceneEvent>
  </Events>
</Scenario>
